/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PoliticaDePrivacidadeRouteImport } from './routes/politica-de-privacidade'
import { Route as PainelRouteImport } from './routes/painel'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BootstrapRouteImport } from './routes/bootstrap'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PainelIndexRouteImport } from './routes/painel.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PainelWhatsappRouteImport } from './routes/painel.whatsapp'
import { Route as PainelSocialRouteImport } from './routes/painel.social'
import { Route as PainelRedesSociaisRouteImport } from './routes/painel.redes-sociais'
import { Route as PainelLinkRouteImport } from './routes/painel.link'
import { Route as PainelLeadsRouteImport } from './routes/painel.leads'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as AdminWhatsappRouteImport } from './routes/admin.whatsapp'
import { Route as AdminConfiguracoesRouteImport } from './routes/admin.configuracoes'
import { Route as PainelTemplatesIndexRouteImport } from './routes/painel.templates.index'
import { Route as AdminCandidatosIndexRouteImport } from './routes/admin.candidatos.index'
import { Route as PainelTemplatesTplIdRouteImport } from './routes/painel.templates.$tplId'
import { Route as AuthMetaCallbackRouteImport } from './routes/auth.meta.callback'
import { Route as AdminCandidatosIdIndexRouteImport } from './routes/admin.candidatos.$id.index'
import { Route as ApiPublicWhatsappWebhookRouteImport } from './routes/api/public/whatsapp.webhook'
import { Route as ApiPublicWhatsappBroadcastTickRouteImport } from './routes/api/public/whatsapp.broadcast-tick'
import { Route as ApiPublicSocialHealthRouteImport } from './routes/api/public/social.health'
import { Route as ApiPublicSocialCronRouteImport } from './routes/api/public/social.cron'
import { Route as ApiPublicMetaOauthRouteImport } from './routes/api/public/meta.oauth'
import { Route as AdminCandidatosIdTemplateTplIdRouteImport } from './routes/admin.candidatos.$id.template.$tplId'

const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PoliticaDePrivacidadeRoute = PoliticaDePrivacidadeRouteImport.update({
  id: '/politica-de-privacidade',
  path: '/politica-de-privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelRoute = PainelRouteImport.update({
  id: '/painel',
  path: '/painel',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BootstrapRoute = BootstrapRouteImport.update({
  id: '/bootstrap',
  path: '/bootstrap',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PainelIndexRoute = PainelIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PainelRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelWhatsappRoute = PainelWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => PainelRoute,
} as any)
const PainelSocialRoute = PainelSocialRouteImport.update({
  id: '/social',
  path: '/social',
  getParentRoute: () => PainelRoute,
} as any)
const PainelRedesSociaisRoute = PainelRedesSociaisRouteImport.update({
  id: '/redes-sociais',
  path: '/redes-sociais',
  getParentRoute: () => PainelRoute,
} as any)
const PainelLinkRoute = PainelLinkRouteImport.update({
  id: '/link',
  path: '/link',
  getParentRoute: () => PainelRoute,
} as any)
const PainelLeadsRoute = PainelLeadsRouteImport.update({
  id: '/leads',
  path: '/leads',
  getParentRoute: () => PainelRoute,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminWhatsappRoute = AdminWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConfiguracoesRoute = AdminConfiguracoesRouteImport.update({
  id: '/configuracoes',
  path: '/configuracoes',
  getParentRoute: () => AdminRoute,
} as any)
const PainelTemplatesIndexRoute = PainelTemplatesIndexRouteImport.update({
  id: '/templates/',
  path: '/templates/',
  getParentRoute: () => PainelRoute,
} as any)
const AdminCandidatosIndexRoute = AdminCandidatosIndexRouteImport.update({
  id: '/candidatos/',
  path: '/candidatos/',
  getParentRoute: () => AdminRoute,
} as any)
const PainelTemplatesTplIdRoute = PainelTemplatesTplIdRouteImport.update({
  id: '/templates/$tplId',
  path: '/templates/$tplId',
  getParentRoute: () => PainelRoute,
} as any)
const AuthMetaCallbackRoute = AuthMetaCallbackRouteImport.update({
  id: '/auth/meta/callback',
  path: '/auth/meta/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatosIdIndexRoute = AdminCandidatosIdIndexRouteImport.update({
  id: '/candidatos/$id/',
  path: '/candidatos/$id/',
  getParentRoute: () => AdminRoute,
} as any)
const ApiPublicWhatsappWebhookRoute =
  ApiPublicWhatsappWebhookRouteImport.update({
    id: '/api/public/whatsapp/webhook',
    path: '/api/public/whatsapp/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWhatsappBroadcastTickRoute =
  ApiPublicWhatsappBroadcastTickRouteImport.update({
    id: '/api/public/whatsapp/broadcast-tick',
    path: '/api/public/whatsapp/broadcast-tick',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicSocialHealthRoute = ApiPublicSocialHealthRouteImport.update({
  id: '/api/public/social/health',
  path: '/api/public/social/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSocialCronRoute = ApiPublicSocialCronRouteImport.update({
  id: '/api/public/social/cron',
  path: '/api/public/social/cron',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMetaOauthRoute = ApiPublicMetaOauthRouteImport.update({
  id: '/api/public/meta/oauth',
  path: '/api/public/meta/oauth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCandidatosIdTemplateTplIdRoute =
  AdminCandidatosIdTemplateTplIdRouteImport.update({
    id: '/candidatos/$id/template/$tplId',
    path: '/candidatos/$id/template/$tplId',
    getParentRoute: () => AdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/link': typeof PainelLinkRoute
  '/painel/redes-sociais': typeof PainelRedesSociaisRoute
  '/painel/social': typeof PainelSocialRoute
  '/painel/whatsapp': typeof PainelWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/painel/templates/$tplId': typeof PainelTemplatesTplIdRoute
  '/admin/candidatos/': typeof AdminCandidatosIndexRoute
  '/painel/templates/': typeof PainelTemplatesIndexRoute
  '/api/public/meta/oauth': typeof ApiPublicMetaOauthRoute
  '/api/public/social/cron': typeof ApiPublicSocialCronRoute
  '/api/public/social/health': typeof ApiPublicSocialHealthRoute
  '/api/public/whatsapp/broadcast-tick': typeof ApiPublicWhatsappBroadcastTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/admin/candidatos/$id/': typeof AdminCandidatosIdIndexRoute
  '/admin/candidatos/$id/template/$tplId': typeof AdminCandidatosIdTemplateTplIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bootstrap': typeof BootstrapRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/link': typeof PainelLinkRoute
  '/painel/redes-sociais': typeof PainelRedesSociaisRoute
  '/painel/social': typeof PainelSocialRoute
  '/painel/whatsapp': typeof PainelWhatsappRoute
  '/admin': typeof AdminIndexRoute
  '/painel': typeof PainelIndexRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/painel/templates/$tplId': typeof PainelTemplatesTplIdRoute
  '/admin/candidatos': typeof AdminCandidatosIndexRoute
  '/painel/templates': typeof PainelTemplatesIndexRoute
  '/api/public/meta/oauth': typeof ApiPublicMetaOauthRoute
  '/api/public/social/cron': typeof ApiPublicSocialCronRoute
  '/api/public/social/health': typeof ApiPublicSocialHealthRoute
  '/api/public/whatsapp/broadcast-tick': typeof ApiPublicWhatsappBroadcastTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/admin/candidatos/$id': typeof AdminCandidatosIdIndexRoute
  '/admin/candidatos/$id/template/$tplId': typeof AdminCandidatosIdTemplateTplIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/bootstrap': typeof BootstrapRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/painel': typeof PainelRouteWithChildren
  '/politica-de-privacidade': typeof PoliticaDePrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/admin/configuracoes': typeof AdminConfiguracoesRoute
  '/admin/whatsapp': typeof AdminWhatsappRoute
  '/p/$slug': typeof PSlugRoute
  '/painel/leads': typeof PainelLeadsRoute
  '/painel/link': typeof PainelLinkRoute
  '/painel/redes-sociais': typeof PainelRedesSociaisRoute
  '/painel/social': typeof PainelSocialRoute
  '/painel/whatsapp': typeof PainelWhatsappRoute
  '/admin/': typeof AdminIndexRoute
  '/painel/': typeof PainelIndexRoute
  '/auth/meta/callback': typeof AuthMetaCallbackRoute
  '/painel/templates/$tplId': typeof PainelTemplatesTplIdRoute
  '/admin/candidatos/': typeof AdminCandidatosIndexRoute
  '/painel/templates/': typeof PainelTemplatesIndexRoute
  '/api/public/meta/oauth': typeof ApiPublicMetaOauthRoute
  '/api/public/social/cron': typeof ApiPublicSocialCronRoute
  '/api/public/social/health': typeof ApiPublicSocialHealthRoute
  '/api/public/whatsapp/broadcast-tick': typeof ApiPublicWhatsappBroadcastTickRoute
  '/api/public/whatsapp/webhook': typeof ApiPublicWhatsappWebhookRoute
  '/admin/candidatos/$id/': typeof AdminCandidatosIdIndexRoute
  '/admin/candidatos/$id/template/$tplId': typeof AdminCandidatosIdTemplateTplIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/configuracoes'
    | '/admin/whatsapp'
    | '/p/$slug'
    | '/painel/leads'
    | '/painel/link'
    | '/painel/redes-sociais'
    | '/painel/social'
    | '/painel/whatsapp'
    | '/admin/'
    | '/painel/'
    | '/auth/meta/callback'
    | '/painel/templates/$tplId'
    | '/admin/candidatos/'
    | '/painel/templates/'
    | '/api/public/meta/oauth'
    | '/api/public/social/cron'
    | '/api/public/social/health'
    | '/api/public/whatsapp/broadcast-tick'
    | '/api/public/whatsapp/webhook'
    | '/admin/candidatos/$id/'
    | '/admin/candidatos/$id/template/$tplId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/bootstrap'
    | '/cadastro'
    | '/login'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/configuracoes'
    | '/admin/whatsapp'
    | '/p/$slug'
    | '/painel/leads'
    | '/painel/link'
    | '/painel/redes-sociais'
    | '/painel/social'
    | '/painel/whatsapp'
    | '/admin'
    | '/painel'
    | '/auth/meta/callback'
    | '/painel/templates/$tplId'
    | '/admin/candidatos'
    | '/painel/templates'
    | '/api/public/meta/oauth'
    | '/api/public/social/cron'
    | '/api/public/social/health'
    | '/api/public/whatsapp/broadcast-tick'
    | '/api/public/whatsapp/webhook'
    | '/admin/candidatos/$id'
    | '/admin/candidatos/$id/template/$tplId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/bootstrap'
    | '/cadastro'
    | '/login'
    | '/painel'
    | '/politica-de-privacidade'
    | '/termos-de-uso'
    | '/admin/configuracoes'
    | '/admin/whatsapp'
    | '/p/$slug'
    | '/painel/leads'
    | '/painel/link'
    | '/painel/redes-sociais'
    | '/painel/social'
    | '/painel/whatsapp'
    | '/admin/'
    | '/painel/'
    | '/auth/meta/callback'
    | '/painel/templates/$tplId'
    | '/admin/candidatos/'
    | '/painel/templates/'
    | '/api/public/meta/oauth'
    | '/api/public/social/cron'
    | '/api/public/social/health'
    | '/api/public/whatsapp/broadcast-tick'
    | '/api/public/whatsapp/webhook'
    | '/admin/candidatos/$id/'
    | '/admin/candidatos/$id/template/$tplId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BootstrapRoute: typeof BootstrapRoute
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  PainelRoute: typeof PainelRouteWithChildren
  PoliticaDePrivacidadeRoute: typeof PoliticaDePrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  PSlugRoute: typeof PSlugRoute
  AuthMetaCallbackRoute: typeof AuthMetaCallbackRoute
  ApiPublicMetaOauthRoute: typeof ApiPublicMetaOauthRoute
  ApiPublicSocialCronRoute: typeof ApiPublicSocialCronRoute
  ApiPublicSocialHealthRoute: typeof ApiPublicSocialHealthRoute
  ApiPublicWhatsappBroadcastTickRoute: typeof ApiPublicWhatsappBroadcastTickRoute
  ApiPublicWhatsappWebhookRoute: typeof ApiPublicWhatsappWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/politica-de-privacidade': {
      id: '/politica-de-privacidade'
      path: '/politica-de-privacidade'
      fullPath: '/politica-de-privacidade'
      preLoaderRoute: typeof PoliticaDePrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel': {
      id: '/painel'
      path: '/painel'
      fullPath: '/painel'
      preLoaderRoute: typeof PainelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bootstrap': {
      id: '/bootstrap'
      path: '/bootstrap'
      fullPath: '/bootstrap'
      preLoaderRoute: typeof BootstrapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/painel/': {
      id: '/painel/'
      path: '/'
      fullPath: '/painel/'
      preLoaderRoute: typeof PainelIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/whatsapp': {
      id: '/painel/whatsapp'
      path: '/whatsapp'
      fullPath: '/painel/whatsapp'
      preLoaderRoute: typeof PainelWhatsappRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/social': {
      id: '/painel/social'
      path: '/social'
      fullPath: '/painel/social'
      preLoaderRoute: typeof PainelSocialRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/redes-sociais': {
      id: '/painel/redes-sociais'
      path: '/redes-sociais'
      fullPath: '/painel/redes-sociais'
      preLoaderRoute: typeof PainelRedesSociaisRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/link': {
      id: '/painel/link'
      path: '/link'
      fullPath: '/painel/link'
      preLoaderRoute: typeof PainelLinkRouteImport
      parentRoute: typeof PainelRoute
    }
    '/painel/leads': {
      id: '/painel/leads'
      path: '/leads'
      fullPath: '/painel/leads'
      preLoaderRoute: typeof PainelLeadsRouteImport
      parentRoute: typeof PainelRoute
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/whatsapp': {
      id: '/admin/whatsapp'
      path: '/whatsapp'
      fullPath: '/admin/whatsapp'
      preLoaderRoute: typeof AdminWhatsappRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/configuracoes': {
      id: '/admin/configuracoes'
      path: '/configuracoes'
      fullPath: '/admin/configuracoes'
      preLoaderRoute: typeof AdminConfiguracoesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/templates/': {
      id: '/painel/templates/'
      path: '/templates'
      fullPath: '/painel/templates/'
      preLoaderRoute: typeof PainelTemplatesIndexRouteImport
      parentRoute: typeof PainelRoute
    }
    '/admin/candidatos/': {
      id: '/admin/candidatos/'
      path: '/candidatos'
      fullPath: '/admin/candidatos/'
      preLoaderRoute: typeof AdminCandidatosIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/painel/templates/$tplId': {
      id: '/painel/templates/$tplId'
      path: '/templates/$tplId'
      fullPath: '/painel/templates/$tplId'
      preLoaderRoute: typeof PainelTemplatesTplIdRouteImport
      parentRoute: typeof PainelRoute
    }
    '/auth/meta/callback': {
      id: '/auth/meta/callback'
      path: '/auth/meta/callback'
      fullPath: '/auth/meta/callback'
      preLoaderRoute: typeof AuthMetaCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidatos/$id/': {
      id: '/admin/candidatos/$id/'
      path: '/candidatos/$id'
      fullPath: '/admin/candidatos/$id/'
      preLoaderRoute: typeof AdminCandidatosIdIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/api/public/whatsapp/webhook': {
      id: '/api/public/whatsapp/webhook'
      path: '/api/public/whatsapp/webhook'
      fullPath: '/api/public/whatsapp/webhook'
      preLoaderRoute: typeof ApiPublicWhatsappWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/whatsapp/broadcast-tick': {
      id: '/api/public/whatsapp/broadcast-tick'
      path: '/api/public/whatsapp/broadcast-tick'
      fullPath: '/api/public/whatsapp/broadcast-tick'
      preLoaderRoute: typeof ApiPublicWhatsappBroadcastTickRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/health': {
      id: '/api/public/social/health'
      path: '/api/public/social/health'
      fullPath: '/api/public/social/health'
      preLoaderRoute: typeof ApiPublicSocialHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/social/cron': {
      id: '/api/public/social/cron'
      path: '/api/public/social/cron'
      fullPath: '/api/public/social/cron'
      preLoaderRoute: typeof ApiPublicSocialCronRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/meta/oauth': {
      id: '/api/public/meta/oauth'
      path: '/api/public/meta/oauth'
      fullPath: '/api/public/meta/oauth'
      preLoaderRoute: typeof ApiPublicMetaOauthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/candidatos/$id/template/$tplId': {
      id: '/admin/candidatos/$id/template/$tplId'
      path: '/candidatos/$id/template/$tplId'
      fullPath: '/admin/candidatos/$id/template/$tplId'
      preLoaderRoute: typeof AdminCandidatosIdTemplateTplIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminConfiguracoesRoute: typeof AdminConfiguracoesRoute
  AdminWhatsappRoute: typeof AdminWhatsappRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminCandidatosIndexRoute: typeof AdminCandidatosIndexRoute
  AdminCandidatosIdIndexRoute: typeof AdminCandidatosIdIndexRoute
  AdminCandidatosIdTemplateTplIdRoute: typeof AdminCandidatosIdTemplateTplIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminConfiguracoesRoute: AdminConfiguracoesRoute,
  AdminWhatsappRoute: AdminWhatsappRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminCandidatosIndexRoute: AdminCandidatosIndexRoute,
  AdminCandidatosIdIndexRoute: AdminCandidatosIdIndexRoute,
  AdminCandidatosIdTemplateTplIdRoute: AdminCandidatosIdTemplateTplIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface PainelRouteChildren {
  PainelLeadsRoute: typeof PainelLeadsRoute
  PainelLinkRoute: typeof PainelLinkRoute
  PainelRedesSociaisRoute: typeof PainelRedesSociaisRoute
  PainelSocialRoute: typeof PainelSocialRoute
  PainelWhatsappRoute: typeof PainelWhatsappRoute
  PainelIndexRoute: typeof PainelIndexRoute
  PainelTemplatesTplIdRoute: typeof PainelTemplatesTplIdRoute
  PainelTemplatesIndexRoute: typeof PainelTemplatesIndexRoute
}

const PainelRouteChildren: PainelRouteChildren = {
  PainelLeadsRoute: PainelLeadsRoute,
  PainelLinkRoute: PainelLinkRoute,
  PainelRedesSociaisRoute: PainelRedesSociaisRoute,
  PainelSocialRoute: PainelSocialRoute,
  PainelWhatsappRoute: PainelWhatsappRoute,
  PainelIndexRoute: PainelIndexRoute,
  PainelTemplatesTplIdRoute: PainelTemplatesTplIdRoute,
  PainelTemplatesIndexRoute: PainelTemplatesIndexRoute,
}

const PainelRouteWithChildren =
  PainelRoute._addFileChildren(PainelRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BootstrapRoute: BootstrapRoute,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  PainelRoute: PainelRouteWithChildren,
  PoliticaDePrivacidadeRoute: PoliticaDePrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  PSlugRoute: PSlugRoute,
  AuthMetaCallbackRoute: AuthMetaCallbackRoute,
  ApiPublicMetaOauthRoute: ApiPublicMetaOauthRoute,
  ApiPublicSocialCronRoute: ApiPublicSocialCronRoute,
  ApiPublicSocialHealthRoute: ApiPublicSocialHealthRoute,
  ApiPublicWhatsappBroadcastTickRoute: ApiPublicWhatsappBroadcastTickRoute,
  ApiPublicWhatsappWebhookRoute: ApiPublicWhatsappWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
