// This file is automatically generated. Do not edit it directly.
// Server-side Supabase client with service role key - bypasses RLS.
// Use this for admin operations in server functions and server routes only.
// For user-authenticated queries (with RLS), use the auth middleware instead.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { normalizeSupabaseUrl } from './url';

function createSupabaseAdminClient() {
  const processUrl = normalizeSupabaseUrl(process.env.SUPABASE_URL);
  const processViteUrl = normalizeSupabaseUrl(process.env.VITE_SUPABASE_URL);
  const importMetaViteUrl = normalizeSupabaseUrl(import.meta.env.VITE_SUPABASE_URL);
  const SUPABASE_URL =
    processUrl ||
    processViteUrl ||
    importMetaViteUrl ||
    "https://pfppmkqsdqawvykkgafe.supabase.co";
  const SUPABASE_SERVICE_ROLE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY;

  console.log("[supabase.admin] ENV CHECK", {
    SUPABASE_URL: !!process.env.SUPABASE_URL,
    PROCESS_VITE_SUPABASE_URL: !!process.env.VITE_SUPABASE_URL,
    IMPORT_META_VITE_SUPABASE_URL: !!import.meta.env.VITE_SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: !!SUPABASE_SERVICE_ROLE_KEY,
    resolvedSupabaseUrlSource: processUrl
      ? "process.env.SUPABASE_URL"
      : processViteUrl
        ? "process.env.VITE_SUPABASE_URL"
        : importMetaViteUrl
          ? "import.meta.env.VITE_SUPABASE_URL"
          : "fallback.constant",
  });

  if (!SUPABASE_SERVICE_ROLE_KEY) {
    const message = `Missing Supabase environment variable: SUPABASE_SERVICE_ROLE_KEY. Defina essa variável no ambiente do servidor (VPS / EasyPanel).`;
    console.error(`[Supabase] ${message}`);
    throw new Error(message);
  }


  return createClient<Database>(SUPABASE_URL, SUPABASE_SERVICE_ROLE_KEY, {
    auth: {
      storage: undefined,
      persistSession: false,
      autoRefreshToken: false,
    }
  });
}

let _supabaseAdmin: ReturnType<typeof createSupabaseAdminClient> | undefined;

// Server-side Supabase client with service role - bypasses RLS
// SECURITY: Only use this for trusted server-side operations, never expose to client code
// Import like: import { supabaseAdmin } from "@/integrations/supabase/client.server";
export const supabaseAdmin = new Proxy({} as ReturnType<typeof createSupabaseAdminClient>, {
  get(_, prop, receiver) {
    if (!_supabaseAdmin) _supabaseAdmin = createSupabaseAdminClient();
    return Reflect.get(_supabaseAdmin, prop, receiver);
  },
});
